steps:
  - name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ['install', '--ignore-scripts']

  - name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ['run', 'build:server']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env', 'dist/.env']
    env:
      - 'ANIWATCH_API_WINDOW_MS=${_ANIWATCH_API_WINDOW_MS}'
      - 'ANIWATCH_API_MAX_REQS=${_ANIWATCH_API_MAX_REQS}'
      - 'ANIWATCH_API_HOSTNAME=${_ANIWATCH_API_HOSTNAME}'
      - 'ANIWATCH_API_DEPLOYMENT_ENV=${_ANIWATCH_API_DEPLOYMENT_ENV}'
      - 'ANIWATCH_API_S_MAXAGE=${_ANIWATCH_API_S_MAXAGE}'
      - 'ANIWATCH_API_STALE_WHILE_REVALIDATE=${_ANIWATCH_API_STALE_WHILE_REVALIDATE}'
      - 'ANIWATCH_API_REDIS_CONN_URL=${_ANIWATCH_API_REDIS_CONN_URL}'
      - 'ANIWATCH_API_PORT=${_ANIWATCH_API_PORT}'
      
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'api',
        '--source',
        '.',
        '--region=asia-southeast1',
        '--memory=4G',
        '--cpu=4',
      ]
    dir: 'dist'

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY